import requests

from app.core.config import (
    LM_STUDIO_URL,
    MODEL_NAME,
)

from app.utils.prompts import (
    build_medical_prompt,
)


def analyze_symptoms(
    symptoms: str,
) -> str:

    prompt = build_medical_prompt(
        symptoms,
    )

    payload = {

        "model": MODEL_NAME,

        "messages": [
            {
                "role": "user",
                "content": prompt
            }
        ],

       
        "temperature": 0.4,

        # IMPORTANT
        "max_tokens": 250,

       
        "stream": False,
    }

    headers = {
        "Content-Type": "application/json"
    }

    try:

        response = requests.post(

            LM_STUDIO_URL,

            json=payload,

            headers=headers,

            timeout=300,
        )


        
        response.raise_for_status()


       
        result = response.json()


        # SAFETY CHECK
        if "choices" not in result:

            raise Exception(
                f"Invalid LM Studio response: {result}"
            )


        choices = result.get("choices")


        if not choices:

            raise Exception(
                "No response generated by AI model."
            )


        message = choices[0].get("message")


        if not message:

            raise Exception(
                "Missing message in AI response."
            )


        content = message.get("content")


        if not content:

            raise Exception(
                "AI returned empty content."
            )


        return content.strip()


    except requests.exceptions.Timeout:

        raise Exception(
            "AI model took too long to respond."
        )


    except requests.exceptions.ConnectionError:

        raise Exception(
            "Could not connect to LM Studio."
        )


    except requests.exceptions.RequestException as e:

        raise Exception(
            f"Request failed: {str(e)}"
        )


    except ValueError:

        raise Exception(
            "Invalid JSON received from LM Studio."
        )


    except Exception as e:

        raise Exception(str(e))